name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  shelf_modular: ^2.0.0
  dotenv: ^4.0.1
  mysql_client: ^0.0.24
  shelf_swagger_ui: ^1.0.0+2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.4.1
